// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package logif

import "strconv"

const (
	_LogLevel_name_0 = "DEBUG"
	_LogLevel_name_1 = "INFOWARNERRORFATALPANIC"
)

var (
	_LogLevel_index_1 = [...]uint8{0, 4, 8, 13, 18, 23}
)

func (i LogLevel) String() string {
	switch {
	case i == 0:
		return _LogLevel_name_0
	case 2 <= i && i <= 6:
		i -= 2
		return _LogLevel_name_1[_LogLevel_index_1[i]:_LogLevel_index_1[i+1]]
	default:
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
